name: CI
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-lasted

    steps:
      - uses: actions/checkout@v1
      - name: Get Node.js
      - uses: actions/setup-node@v1
        with:
          node-verion: 12
      - name: Install dependecies
        run: yarn
      - name: Testing
        run: CI=true yarn test
      - name: Build
        run: yarn build
